### ISSUE TITLE
Should we allow editors to view list of users?

### ISSUE THREAD

**Issue by genjohnson** [uiowa/rusty#101]
A common cause of confusion and support requests is that users with the "editor" role are unaware of who has a user account on the website and what role/permissions each user has.

Should we allow users with the "editor" role to (only) view the list of users at `/admin/people`?

**Comment by richardbporter** [comment]
I would say so, yes.

**Comment by richardbporter** [comment]
Granting editors the 'administer users' permission and configuring userprotect almost works. Unfortunately, there is some goofy behavior with this including editors canceling their own accounts and escalating permissions through bulk operations.

**Comment by richardbporter** [comment]
Uh oh. I'm seeing duplicate users listed after assigning users multiple roles. 

Probably much like: https://github.com/ITS-UofIowa/sitenow_standard_profile/pull/183

**Comment by richardbporter** [comment]
The roleassign module is causing the escalation of privileges. We should swap with role_delegation.
