### ISSUE TITLE
Should uiowa_footer use hook_page_bottom()?

### ISSUE THREAD

**Issue by genjohnson** [uiowa/rusty#117]
The module uiowa_footer currently provides a block to be placed in the footer. Should the output instead be added to the page using `hook_page_bottom()`, similar to how uiowa_bar is using `hook_page_top()`?

**Comment by genjohnson** [comment]
The output from uiowa_footer should only ever be displayed at the bottom of the page, so using `hook_page_bottom()` makes more sense to me than using a block... one less item to clutter the block interface :)

**Comment by joewhitsitt** [comment]
`hook_page_bottom()` makes sense to me

**Comment by joewhitsitt** [comment]
Went with page_bottom - https://github.com/uiowa/rusty/pull/118/commits/e319b0fb1f1273c169415c241c21e317f3aedc37
