### ISSUE TITLE
Paragraphs: Investigate options to make node/edit form more "readable"

### ISSUE THREAD

**Issue by genjohnson** [uiowa/rusty#127]
Investigate ways to make the edit form more "readable", for example by reducing the depth of nesting

**Comment by joewhitsitt** [comment]
At least in terms of Accordion, turning building Accordion Item as a multifield field type, multivalue field widget would reduce nesting by one and still allow reordering.

**Comment by joewhitsitt** [comment]
Actually, though it does reduce one level of paragraph nesting, the custom FieldType alternative is unruly in another way... see below. It could be cleaned up using field group's details option, but it still wouldn't solve any potential issues related to max_input_vars like we have run into in the past.

![eight uiowa lndo site_node_1_edit_destination _admin_content](https://user-images.githubusercontent.com/4663676/46413344-51aefb80-c6e6-11e8-8320-ec36a1593b0f.png)
