### ISSUE TITLE
Indicate the environment in the toolbar.

### ISSUE THREAD

**Issue by richardbporter** [uiowa/rusty#128]
This would be nice to quickly differentiate environments. Ex. https://www.drupal.org/project/simplei

**Comment by richardbporter** [comment]
These modules require using settings. I think the less we manage in https://github.com/uiowa/multisite, the better. We should just implement a hook in the rusty to accomplish this.

**Comment by adamdelaney** [comment]
@richardbporter  hook_krome_js() ;)
