### ISSUE TITLE
Update menu_block patch

### ISSUE THREAD

**Issue by genjohnson** [uiowa/rusty#131]
A new version of the patch to "Add option to make the starting level follow the active menu item" is available in [comment #55](https://www.drupal.org/project/menu_block/issues/2756675#comment-12722484)

If the patch in comment 55 works, we should also check if we can apply the patches for:
- Menu parent as block title: https://www.drupal.org/project/menu_block/issues/2809699
- Add links to menu parent block title: https://www.drupal.org/project/menu_block/issues/2950943

**Comment by briand44** [comment]
Postponed this issue until we figure out #165

**Comment by richardbporter** [comment]
Issue 2757215 has been committed to latest dev. I'm not going to worry about the other issues right now.

**Comment by richardbporter** [comment]
The second patch we have on menu_block does not apply after the update: https://www.drupal.org/project/menu_block/issues/2757215

Closing for now.
