### ISSUE TITLE
Paragraphs: Container and alignment options

### ISSUE THREAD

**Issue by adamdelaney** [uiowa/rusty#140]
Investigate adding container and flex align-items options for sections.

**Comment by joewhitsitt** [comment]
this was added
<img width="676" alt="screen shot 2018-10-30 at 4 01 17 pm" src="https://user-images.githubusercontent.com/4663676/47750361-3c81aa00-dc5d-11e8-80e5-89294afbac87.png">

**Comment by joewhitsitt** [comment]
Though the form UI has changed for this, it still exists in the feature branch. Closing
