### ISSUE TITLE
Field Naming Conventions

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/rusty#141]
The issue of naming conventions came up, and despite my best efforts I am having troubles finding our previous discussion on this topic. Please let me know if this is being discussed elsewhere.

The current feature branch uiowa_paragraphs_attributes is not a good model and I was going to refactor it to make it better, before I do below is my thought process/rationale. Chime in if you think differently.

core/contrib field types shared across multiple entities:
field_{what it is}{plural if multiple} (e.g. field_teaser)

unique to the entity/bundle:
field_{entity/bundle}_{what it is}{plural if multiple} (e.g. field_section_content_blocks)

custom uiowa developed field type shared across multiple entities:
field_uiowa_{what it is}{plural if multiple}
OR module specific:
field_{abbr. module}_{what it is}{plural if multiple} (e.g. field_up_attributes for uiowa_paragraphs attributes field type)

**Comment by genjohnson** [comment]
+1

These patterns make sense to me and seem to be in line with the conventions we adopted with Drupal 7 (which I think has worked well).

Since we chatted about this, I just want to add the rationale behind abbreviating some module names...that we do this because of the character length constraint on the file names. For example, we may use `field_up_attributes` instead of `field_uiowa_paragraphs_attributes` due to the length.

**Comment by pyrello** [comment]
The only part that I'm not sure about is the abbr. module part of the module-specific custom uiowa field type. Even with the explanation, it took me a moment to realize what "up" was.

**Comment by joewhitsitt** [comment]
i assume we will have a uiowa_people or uiowa_person for the person content type which will conflict with the up prefix... so maybe that abbreviation is too short to be understandable...

**Comment by joewhitsitt** [comment]
ui_par? ui_peo?

ui_{first three?)

**Comment by adamdelaney** [comment]
I vote for `field_ui_{max_5_char}`

**Comment by joewhitsitt** [comment]
that would allow field_ui_peeps_{something} for uiowa_people 😆 , and field_ui_maps_{something}, etc.

**Comment by joewhitsitt** [comment]
There was a ITS in-person discussion. I am moving forward with field_uip_... for uiowa_paragraphs specifically (p stands for `<p>` which stands for paragraph), and further work should but is not limited to some sort of field_ui{prefix}_{what it is}, where prefix is related to where/owner of the field.

**Comment by genjohnson** [comment]
It sounds like this had been resolved. Feel free to re-open if continued discussion is needed.
