### ISSUE TITLE
Users listed multiple times when assigned multiple roles

### ISSUE THREAD

**Issue by richardbporter** [uiowa/rusty#147]
Related: https://github.com/ITS-UofIowa/sitenow_standard_profile/issues/160

**Comment by genjohnson** [comment]
I think the query alter can be removed now that we're using Administer Users by Role

**Comment by richardbporter** [comment]
It seems to filter out user 1 but not other administrators - at least that is what I was seeing. Try adding another user with admin role.

There is no reduceDuplicates() method and setting `$query->distinct` to true didn't fix it either.

**Comment by genjohnson** [comment]
I wonder what the difference between our sites is....

I removed `rusty_views_query_alter()` and installed a fresh site. I added an another administrator account, an editor and a webmaster.

As user 1, I can see all of the user accounts:
![screenshot 2018-11-07 16 41 46](https://user-images.githubusercontent.com/1282401/48165828-73367080-e2ac-11e8-841b-8ff98fa176ea.png)

As a webmaster (Herky), I can only see the non-admin user accounts:
![screenshot 2018-11-07 16 42 08](https://user-images.githubusercontent.com/1282401/48165848-821d2300-e2ac-11e8-97cb-2fb8b8a58a88.png)

I tried this again with an administrator account that's name did NOT include "admin", and I got the same results, where non-admininstrators could not see any of the administrator accounts.

**Comment by genjohnson** [comment]
@richardbporter I found the magic!! `administerusersbyrole_query_administerusersbyrole_edit_access_alter()` in adminsterusersbyrole.module modifies the user listing results to exclude user accounts that the logged in user does not have permission to modify.

**Comment by richardbporter** [comment]
Resolved by #150
