### ISSUE TITLE
field_teaser tasks

### ISSUE THREAD

**Issue by adamdelaney** [uiowa/rusty#149]
- [x] Set field_teaser as default metatag description for basic pages.
- [x] Move field_teaser to vertical fieldset. Since this is not being rendered on the node and for all intensive purposes metadata we should move it out of the main layout area.
- [x] Provide description text for the field. Our goal with D8 is to document as much information within the site, so providing context to how this field is used with field description makes the most sense.

**Comment by joewhitsitt** [comment]
keep in mind, field_teaser only exists in the uiowa_paragraphs_attributes branch at this time.

**Comment by genjohnson** [comment]
Based on @joewhitsitt's comment above, this is blocked until #154 is resolved.
