### ISSUE TITLE
Identify sites for 1.0.0

### ISSUE THREAD

**Issue by genjohnson** [uiowa/rusty#159]
Identify sites which are good candidates to go live on Drupal 8 at the close of the 1.0.0 milestone.

**Comment by genjohnson** [comment]
Proposed sites:
- CSI site
- sitenow.uiowa.edu (maybe...this would be better waiting for Webforms to be available)

**Comment by richardbporter** [comment]
These look fairly "simple". We may need multiple developers assigned to this to axe suggestions for reasons known to them.

- https://vandervelde.studio.uiowa.edu
- https://transfer.uiowa.edu
- https://cio.uiowa.edu
- https://tile.uiowa.edu
- https://govrel.uiowa.edu
- https://gencounsel.uiowa.edu
- https://lynda.uiowa.edu
- https://foriowa.uiowa.edu
- https://innovation.uiowa.edu

**Comment by adamdelaney** [comment]
We should layout some initial criteria for a 1.0.0 site. I'm not sure what a 1.0.0 site even means, but my initial thoughts are as follows:
- A site that we are the content owners of or have a close relationship to the content owners.
- A site that is small in scope and custom integrations.
- A site that has a small audience or gets little traffic.
- A site where the owner's have very little budget and doesn't mind being a first adopter to a new system.

**Comment by richardbporter** [comment]
I think the criteria you outlined should work fine. Thats what I had in mind with the sites I listed but could be mistaken since I'm not familiar with all of them.

**Comment by genjohnson** [comment]
https://vandervelde.studio.uiowa.edu may not be a good candidate as one of the first sites to move because the site owner was _very_ particular about the design.

**Comment by richardbporter** [comment]
Thanks, I crossed that one off our list.

**Comment by pyrello** [comment]
Grad College sites:
* https://cogscilang.grad.uiowa.edu/
* https://iowasuperfund.uiowa.edu/
* https://rio.urban.uiowa.edu/
* https://toxicology.grad.uiowa.edu/

**Comment by genjohnson** [comment]
I've crossed out itaccessibility because of concerns that the site owner will be on the difficult side/cause more work that we're looking for right now.

I chatted with Romy briefly about this this task last week, and she agrees that cio.uiowa.edu is a good candidate.

**Comment by richardbporter** [comment]
Crossed off MNH and OldCap because they are in the process of migrating to the current D7 standard service.

**Comment by richardbporter** [comment]
The sitenow.uiowa.edu site won't need webforms if we use Workflow to provision sites.

**Comment by richardbporter** [comment]
I think we've identified enough sites and can reference this issue for the list.
