### ISSUE TITLE
Open an issue with AUBR re filtering actions by permission

### ISSUE THREAD

**Issue by genjohnson** [uiowa/rusty#160]
Related to #152, open an issue (feature request) on drupal.org with the administerusersbyrole module to filter the Actions available at admin/people based on the permissions the current user has.

**Comment by genjohnson** [comment]
@richardbporter I thought this was a pretty clear-cut task when we opened it almost a month ago, but looking into the permissions and ABUR module as I tried creating an issue this evening just left me confused.

Based on https://github.com/uiowa/rusty/commit/859c75e174d4f923ab20d2619dec388df717caef and https://github.com/uiowa/rusty/blob/21570d50641fcfaefb19f9168b4bb36c5ec7465d/rusty.profile#L144-L159 I was expecting to see permissions `assign roles`, `cancel users by role` and `edit users by role` defined by the AUBR module, but I'm not finding those permissions in the AUBR module (or any other module).

Could you point me to where these permissions are defined or where they are used in AUBR? Or maybe we could walk through this together early next week?

**Comment by richardbporter** [comment]
https://www.drupal.org/project/administerusersbyrole/issues/3023721
