### ISSUE TITLE
Create a basic UI-branded theme

### ISSUE THREAD

**Issue by genjohnson** [uiowa/rusty#164]
Create a UI-branded theme which will evolve as the UI branding project continues. Major components to style include (not an exhaustive list):
- site header
- top-level menu items (superfish)
- Paragraph bundles
  - Section
  - Cards
  - Accordion groups/items
- basic typography & HTML elements
  - headers
  - links
  - lists
  - tables
- site footer (this might already be done in uiowa_footer)

It was suggested that https://innovation.uiowa.edu/ be used as a starting point.

**Comment by genjohnson** [comment]
This issue is blocked until #163 is resolved.

**Comment by genjohnson** [comment]
For reference, notes about empty regions being rendered (and how to work around this) are available in #66

**Comment by richardbporter** [comment]
Will this be a subtheme of uiowa_bootstrap?

**Comment by richardbporter** [comment]
Moving to https://github.com/uiowa/rusty/issues/164 for further discussion.
