### ISSUE TITLE
Decide on default second level menu design pattern

### ISSUE THREAD

**Issue by genjohnson** [uiowa/rusty#165]
A follow-up to #67, determine and implement one or two options for 2+ level menu items.

In Drupal 7, the go-to solution was a menu block in the sidebar. However, this has become complicated as sites use Paragraphs with full-width sections.

A couple of options may be off-canvas navigation or a drop-down list (similar to Tippie and College of Engineering).

**Comment by adamdelaney** [comment]
@bspeare also mentioned exploring a horizontal menu.

**Comment by joewhitsitt** [comment]
Here is my whiteboard brain dump:

- Superfish fly-outs levels infinity
- Superfish 1-2 levels, active menu trail sidebar
- Superfish 1-2 levels, active menu trail horizontal
- Superfish 1-2 levels, "Tippie" (Education, International) style active menu trail dropdown
- Off-canvas

I am familiar with how they all would work except for the horizontal active trail and off-canvas.
- Are there examples of this horizontal idea and how would several items be handled (wrappped, scroll, collapse, etc.)?
- For the off-canvas, would it be in combination with a header menu on desktop? How would the toggle be displayed to users?

**Comment by genjohnson** [comment]
I've edited the task title to better reflect that the scope of this discussion is only the default configuration which will come "out of the box", as developers may implement something different on a per-site basis.

**Comment by bspeare** [comment]
Would using the Superfish block give us the flexibility to implement Joe's suggestions or is Menu Block the preferred menu implementation?

**Comment by genjohnson** [comment]
@bspeare I'm not sure I understand your question. For context, many of our sites currently use Superfish for 1-2 levels and then Menu Block following the active trail in the sidebar (with the sidebar being problematic for pages with full-width paragraphs). So I wouldn't say Menu Block is a preferred implementation for Drupal 8.

**Comment by joewhitsitt** [comment]
I think for right now for rusty we should move forward with a Superfish header and a active menu trail sidebar with a publishing option to hide sidebar. Long term, I think we want to move away from the hide sidebar after investigating providing block management access and/or doing something with the layout API.
