### ISSUE TITLE
Investigate alternatives to profile inheritence

### ISSUE THREAD

**Issue by genjohnson** [uiowa/rusty#177]
Using profile inheritance is risky - see the [issue Allowing profiles to define a base/parent profile and load them in the correct order](https://www.drupal.org/project/drupal/issues/1356276) and [phenaproxima's comment in the Drupal in Education group](https://groups.drupal.org/node/534485#comment-1163232).

As/if a need arises, investigate alternatives.

**Comment by richardbporter** [comment]
We've decided to use multiple profiles.
