### ISSUE TITLE
Improve and optimize image handling for sections

### ISSUE THREAD

**Issue by adamdelaney** [uiowa/rusty#185]
Users currently struggle with how section background images work with cropping and device viewport. Additionally, we load in a gigantic image file even if the image is being viewed on a small or mobile device. We should be able to leverage the picture element and source set attributes to provide a lighter payload. Developing a strategy for this sooner than later is a good idea since changing could break site design in the future.

**Comment by pyrello** [comment]
Any thoughts about using the responsive image module in D8 core? That would handle setting up some configurable responsive image settings and rendering the correct markup for the <picture> tag. If it wasn't going to be used for other images, then probably this could be handled with a template file to override the image output.

I had been planning on looking into responsive images for my sites to handle this, but I haven't played around with it much yet.

**Comment by adamdelaney** [comment]
We should move the bg-image section render out of the preprocessor and into an image display mode. This will put this config in the CM system and allow us to track changes better.

**Comment by joewhitsitt** [comment]
if we are going this route, the card bundle handles the image the same way. not sure if you mean all images or just the section image.
