### ISSUE TITLE
Installation errors due to unmet config dependencies

### ISSUE THREAD

**Issue by adamdelaney** [uiowa/rusty#188]
Hunting down the root cause of this issue is complicated. This is possibly an order of operations issue where installation configuration is looking for active configuration that has not yet been installed. Attempting to move this config into optional config may resolve the issue but also may cause a cascading effect of unmet config dependencies. Removing the config dependency seems to be the best way to resolve the issue. See: https://github.com/uiowa/rusty/pull/187/commits/ae82014fa5ec67d79db365ccb292aab132f97ccb.

**Comment by joewhitsitt** [comment]
piling on: https://github.com/uiowa/rusty/pull/191/commits/c00dbae62cc3ce5b0cb638e6eb123dc0b06c2644

**Comment by richardbporter** [comment]
This issue (and others like it) would most likely be resolved by the config_split strategy defined in https://github.com/uiowa/rusty/issues/158#issuecomment-445970150.
