### ISSUE TITLE
Default patterns for internal domains

### ISSUE THREAD

**Issue by genjohnson** [uiowa/rusty#194]
## Goal
Decide on and implement patterns for domains created in Acquia Cloud when a site is provisioned.

## Context
When provisioning a new site with the multisite commands, domains are automatically created in Acquia Cloud for each of the environments. For ease of use and to avoid conflicts between projects, we should use a standard set of patterns for the domains.

The ITS team has been using the following patterns for domains of Drupal 7 sites, where `env` is dev, stage, or prod:

| Domain of live site  | Pattern        | Example  |
| ------------------- |-------------| ----------|
| X.uiowa.edu      | X.env.drupal.uiowa.edu | research.uiowa.edu → research.dev.drupal.uiowa.edu |
| Y.X.uiowa.edu      | XY.env.drupal.uiowa.edu      |   hso.research.uiowa.edu → researchhso.dev.drupal.uiowa.edu |
| X.Y (non-uiowa.edu domain) | Y-X.env.drupal.uiowa.edu  |    iaapt.us → us-iaapt.dev.drupal.uiowa.edu|

We cannot have the same domain on multiple docroots, so we will need to either remove the domains for the D7 sites as they move to D8 if we want to use the same patterns OR use a different pattern.

**Comment by genjohnson** [comment]
A couple of ideas from the team meeting on 11/28:

- Append "-d8" just before ".env.". For example, hr-d8.dev.drupal.uiowa.edu
- Use a different subdomain.

**Comment by adamdelaney** [comment]
I like *.env.drupal8.uiowa.edu

**Comment by richardbporter** [comment]
This issue should probably be moved to https://github.com/uiowa/multisite.

**Comment by richardbporter** [comment]
https://github.com/uiowa/multisite/issues/76
