### ISSUE TITLE
Create social media menu, set config defaults

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/rusty#199]
The UIowa footer allows a social media menu and another menu to be selected, however webmasters currently don't have ability to create additional menus. Should this be a thing?

**Comment by joewhitsitt** [comment]
There is a footer menu.

**Comment by joewhitsitt** [comment]
The other option is to create the social media menu for them and not hand out the permission to create new menus. This way we control the name and can target it consistently across all sites if need be. However, there is nothing stopping them from using the footer menu in the social media box and vice versa.

**Comment by richardbporter** [comment]
I don't think we want webmasters creating new menus.

**Comment by joewhitsitt** [comment]
I am going to work on creating the menu on install, settings footer defaults and disabling the fields until we can determine a use-case to change the defaults. The D7 version had the select option in case the site had existing menus they wanted to use for this. Since sites will be all new, it seems logical to set defaults and lock it down.
