### ISSUE TITLE
Add login link to footer.

### ISSUE THREAD

**Issue by richardbporter** [uiowa/rusty#200]
Some of our D7 sites have this, some do not. It would be nice to standardize so people know where to look. Footer seems like a logical place.

**Comment by joewhitsitt** [comment]
I think for now, within uiowa_footer makes sense. hardcoded in the template for now with the possibility of turning this into a checkbox within the config later. Would it go to /user or straight to hawkid auth page?

**Comment by richardbporter** [comment]
Sounds good. Straight to the SAML login endpoint, ex: https://github.com/uiowa/rusty/blob/master/modules/uiowa_auth/uiowa_auth.module#L115

**Comment by richardbporter** [comment]
Moving this to https://github.com/uiowa/uiowa_footer/issues/1
