### ISSUE TITLE
Allow custom classes for paragraph sections and widgets

### ISSUE THREAD

**Issue by adamdelaney** [uiowa/rusty#220]
Ideally the classes would be included from a multi-select list. See: https://api.drupal.org/api/drupal/core%21modules%21options%21options.api.php/function/callback_allowed_values_function/8.2.x.

**Comment by joewhitsitt** [comment]
do you envision the available classes being different per paragraph type? how would the management of these work?

**Comment by adamdelaney** [comment]
Yes, they will have to be. I'm not quite sure how this will work yet. it will depend on what information we have when the field gets rendered. If there is no context to the bundle it is attached to we will have to build different fields. If there is context I'd image we could use the same filed and write logic.

**Comment by richardbporter** [comment]
I think #223 resolved this.
