### ISSUE TITLE
Embracing Javascript and not looking back?

### ISSUE THREAD

**Issue by joewhitsitt** [uiowa/rusty#237]
With the recent PR #236, it assumes javascript is turned on in the browser to function. Are we done writing fallbacks? If so should a `<noscript>` message saying so be included in our sites?

**Comment by adamdelaney** [comment]
I've progressively enhanced the card js link functionality to work without javascript. See PR: https://github.com/uiowa/rusty/pull/248.

**Comment by adamdelaney** [comment]
I can't image someone not having javascript turned on these days, but we should progressively enhance when possible.
