### ISSUE TITLE
Allow paragraph admin titles to be printed

### ISSUE THREAD

**Issue by adamdelaney** [uiowa/rusty#275]
It would be nice to provide a required title field for all paragraph bundles and then optionally display it, similar to blocks.
<img width="460" alt="screen shot 2019-01-16 at 4 14 23 pm" src="https://user-images.githubusercontent.com/1016880/51282122-f01b5000-19a9-11e9-84f7-4e6c239ac757.png">

**Comment by joewhitsitt** [comment]
I am going to deconstruct the one-off admin fields and create a global uip_title for this. As for the display title, I am going to look into adding this feature to section, accordion and events for now (essentially mini-wrappers of content where a title would be helpful).

**Comment by joewhitsitt** [comment]
This got sticky quick. Files all over the place, the section title render needs paragraph type logic to handle background images (bg-color, transparency, etc.) and for events, the admin title is part of the content entity and not the paragraph.

**Comment by joewhitsitt** [comment]
This is done
