### ISSUE TITLE
Poppover.js Uncaught TypeError: Cannot read property 'Default' of undefined

### ISSUE THREAD

**Issue by adamdelaney** [uiowa/rusty#277]
![screen shot 2019-01-16 at 4 32 10 pm](https://user-images.githubusercontent.com/1016880/51282973-48535180-19ac-11e9-8512-c606fc6c4d1d.png)

**Comment by joewhitsitt** [comment]
popper was no longer included and tooltip is a dependency of popover
https://github.com/uiowa/uiowa_bootstrap/pull/32
