### ISSUE TITLE
[META] Investigate layout and component solutions for page building tools

### ISSUE THREAD

**Issue by adamdelaney** [uiowa/rusty#86]
## Overview
This issue should be used as a discussion to generate ideas and document solutions, pitfalls and further the discussion on how to provide an intuitive, flexible and powerful set of page building tools.

## Goals
The layout/theme sub-group identified the following desires for layout & component solutions for page building tools during their first meeting on 5/3/18:
- Have the editor interface more visually (than our current Paragraphs implementation) match the layout which will be displayed to site visitors
- Allow for inline editing (which would be much simpler for editors than expanding nested Paragraphs items)
- Allow editors to clone pages or create templates (for re-using specific components/layouts)

**Comment by adamdelaney** [comment]
I found this article comparing different solutions for page building tools: https://www.mediacurrent.com/blog/editorial-workflow-head-head-paragraphs-vs-entity-embed-vs-panelizer/

**Comment by adamdelaney** [comment]
This project looks interesting. I'm going to try to find some time to evaluate it, but I wanted to document the project page: https://www.drupal.org/project/stacks

**Comment by bspeare** [comment]
# Layout Builder

It looks like Acquia is looking to replace Panelizer with Layout Builder in the Lightning distribution.  

You can check out the meeting notes at https://docs.google.com/document/d/1IX-yGjHBHmwa-ZXgOe-V90HYWiyzI7T5soGENsLn76g/edit# where they discussed fixes to a few issues that we had with Layout Builder:

- Ability to create content from UI
- Not pollute block listing page with content only used in a single layout

There is also a sandbox site link in the notes where you can try out a version of Layout Builder with a block creation option in the settings tray.

**Comment by joewhitsitt** [comment]
# Bootstrap Paragraphs

<img width="1252" alt="screen shot 2018-05-16 at 2 48 19 pm" src="https://user-images.githubusercontent.com/4663676/40140331-4910d002-5918-11e8-964f-72c35f4c64c6.png">

_**I think we can "borrow" a lot of this.**_

The column stuff was not very intuitive.

It didn't work with a bootstrap 4 theme (barrio) [even though the maintainer says it should work for the most part](https://www.drupal.org/project/bootstrap_paragraphs/issues/2861474)

**Comment by adamdelaney** [comment]
## Drupal project - Paragraphs Frontend UI
This projects looks like it brings a lot of enhancements to paragraphs. 
- (Paragraphs Frontend UI projects page) [https://www.drupal.org/project/paragraphs_frontend_ui]

**Comment by joewhitsitt** [comment]
I don't think the layout api is ready for paragraphs, and we have already decided to use the bootstrap framework, so I have created a branch off uiowa_paragraphs called [uiowa_paragraphs_attributes](https://github.com/uiowa/rusty/tree/uiowa_paragraphs_attributes) that provides an compound attributes field. There is a simple column width selection of (fluid, full, quarter, third, half) that allows the editor to choose the width of a paragraph item within a section.

<img width="982" alt="screen shot 2018-10-04 at 3 28 01 pm" src="https://user-images.githubusercontent.com/4663676/46501104-24e40c80-c7ea-11e8-9eb4-4732cbe8961e.png">

See this [codepen](https://codepen.io/joewhitsitt/pen/mzVvXN) for the basic idea and try out the branch using a site with a bootstrap theme or css import.

**Comment by joewhitsitt** [comment]
Regarding the last goal bullet point (clone): This exists and is supposedly a part of inline entity form dev: https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Entity%21Entity.php/function/Entity%3A%3AcreateDuplicate/8.6.x

**Comment by adamdelaney** [comment]
Looks like it's part of the entity api not inline entity form.

**Comment by joewhitsitt** [comment]
kapow! https://www.drupal.org/project/inline_entity_form/issues/2962706
