### ISSUE TITLE
SEO related webmaster documentation

### ISSUE THREAD

**Issue by dhannad** [uiowa/rusty#90]
Create documentation for what editors can do regarding per-node metatags, how webmasters should handle sitemap submission, etc.
Specifics:
- [ ] Google webmaster tools, sitemap submission
- Per-node metatag settings
  - [ ] Description (Abstraction)
  - Advanced Tags
    - [ ] Google News Keywords
    - [ ] Image
    - [ ] Canonical URL
    - [ ] Shortlink URL
    - [ ] Original Source
    - Robots (possibly)

**Comment by genjohnson** [comment]
This is related to #88

**Comment by genjohnson** [comment]
Closing as a duplicate of #207.
